export const MAIN_PAGE_ROUTE = '/'
export const PERSONAL_ROUTE = '/personal-account'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PARKING_ROUTE = '/parking'
export const PARKING_PLACE_ROUTE = '/parking_place'
export const LEVEL_ROUTE = '/level/:id'
export const ADMIN_ROUTE = '/admin'